---
version: 2

templates:
  filter_all: &filter_all
    filters:
      tags:
        only: /.*/
      branches:
        only: /.*/

jobs:
  test_node_10:
    docker:
      - image: circleci/node:10
    working_directory: ~/src
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Test Node10
          command: npm test
          environment:
            NODE_ENV: test

  test_node_12:
    docker:
      - image: circleci/node:12
    working_directory: ~/src
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Test Node12
          command: npm test
          environment:
            NODE_ENV: test

workflows:
  version: 2
  test:
    jobs:
      - test_node_10:
          <<: *filter_all
      - test_node_12:
          <<: *filter_all
