name: CI

on:
  push:

jobs:
  test_node_10:
    name: Test node 10
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Node10.x
        uses: actions/setup-node@v3
        with:
          node-version: '10.x'
      -
        run: npm ci
      -
        run: npm test

  test_node_12:
    name: Test node 12
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Node12.x
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      -
        run: npm ci
      -
        run: npm test
